config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/contacts/:provider/contact_callback" => "contacts#download"
  get "/contacts/failure" => "contacts#failure"
  root 'welcome#index'
    
      resources :contacts
  get 'authenticate' => 'import#authenticate'
    

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessor :phone_number
  has_many :phone_numbers, dependent: :destroy
  belongs_to :user


  after_find :get_phone_number
  after_save :save_phone_numbers

  # validates :email, presence: true, format: Devise.email_regexp
  validates_presence_of :name
  validate :phone_number_value

  include PgSearch

  pg_search_scope :search, against:[:name,:email,:address],
  :using => {:tsearch => {:prefix => true}},
  :ignoring => :accents,  
  associated_against: {phone_numbers: :number}
  
  # def self.search(query)
  #   if query.present?
  #     search_by_name(query)
  #   else
  #     # No query? Return all records, newest first.
  #     search_by_name('%')
  #   end
  # end

  def phone_number_value
    # byebug

    if self.phone_number.present?
      numbers_array = self.phone_number.split(",")
      numbers_array.each do |nn|
      nn = nn.gsub("-","").gsub("+91","").gsub(" ","")      
      # byebug
        if nn.to_i.to_s.length != 10
          # byebug
          self.errors[:phone_number]<< "must be 10 digit number"
        end      
      end
    end
  end

  def get_phone_number
    numbers = self.phone_numbers
    self.phone_number = ""
    numbers.each do |nn|
      self.phone_number+= "#{nn.number},"
    end 
    self.phone_number = self.phone_number[0..-2]
  end

  def self.to_csv
    attributes = %w{id name email phone_number address }

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |contact|
        csv << attributes.map{ |attr| contact.send(attr) }
      end
    end
  end  

    def save_phone_numbers
        # byebug
      if self.phone_number.present?
       # byebug  
        numbers_array = self.phone_number.split(",")
        self.phone_numbers.destroy_all
        
        numbers_array.each do |n|
          n = n.gsub("-","").gsub("+91","").gsub("","").to_i
         new_number = PhoneNumber.new(contact_id: id, number: n)
         new_number.save()
        end
      end
    end



    # def self.text_search(query)
    #   if query.present?
    #     rank = <<-RANK
    #   ts_rank(to_tsvector(name), plainto_tsquery(#{sanitize(query)})) +
    #   ts_rank(to_tsvector(email), plainto_tsquery(#{sanitize(query)})) +
    #   ts_rank(to_tsvector(address), plainto_tsquery(#{sanitize(query)})) + 
    #   ts_rank(to_tsvector(number), plainto_tsquery(#{sanitize(query)})) 
      

    # RANK
    # where("to_tsvector('english', name) @@ :q or to_tsvector('english', email) @@ :q or to_tsvector('english', address) @@ :q or to_tsvector('english', number) @@ :q", q: query).order("#{rank} desc")
    #   else
    #      where(nil)
    #   end
    # end
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :contact
  validates_presence_of :contact_id, :number
  validates_numericality_of :number
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
 
  layout 'contact'
  def new 
      
  end

  def create    
    
    contact = current_user.contacts.new(contact_params)
     
    if contact.save
      flash[:notice]=" Contact created successfully"
      redirect_to contacts_path
    else
      flash[:alert]= contact.errors.full_messages
      render 'new'
    end
  end

  def index
    if params[:query].present?
      @contacts = current_user.contacts.search(params[:query]).page(params[:page]).per_page(3)
    else
      @contacts = current_user.contacts.page(params[:page]).per_page(3)
    end  
    respond_to do |format|
      format.html
      format.csv { send_data @contacts.to_csv}
    end
  end

  def show
    @contact = Contact.find_by_id(params[:id])
    @phone_numbers= @contact.phone_numbers
  end

  def edit
    # byebug
    @contact = Contact.find_by_id(params[:id])
    # @phone_numbers = @contact.phone_numbers
  end

  def update

    @contact = Contact.find_by_id(params[:id])
    if @contact.update_attributes(contact_params)
      flash[:notice]=" Contact updated successfully"
      redirect_to contacts_path
    else
      flash[:alert]= @contact.errors.full_messages
      redirect_to edit_contact_path
    end
    
  end

  def destroy
    Contact.find_by_id(params[:id]).destroy
    flash[:notice]=" Contact dated successfully"
    redirect_to contacts_path
  end

  def download
    @contacts = request.env['omnicontacts.contacts']
    count = 0
     # byebug
    if @contacts.present? 
      @contacts.each do |contact|
        # byebug
        # if contact.present?
        #  byebug
        # end 
        contact = current_user.contacts.new(name: contact[:name], address: contact[:addresses], email: contact[:email], phone_number: contact[:phone_numbers].map{|y| y[:number]}.join(","))
        if contact.save
          count +=1
        end
      end
      flash[:notice]= "#{count} Contact created successfully"
      redirect_to contacts_path
    else
      flash[:notice]= " unable to import contacts"
      redirect_to contacts_path
    end

    # respond_to do |format|
    #   format.html
    # end
  end

  private

    def contact_params
      params.require(:contact).permit(:name, :email, :address, :phone_number)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%if current_user %>

        <li><%= link_to destroy_user_session_path do %><span class="glyphicon glyphicon-log-in"></span> Sign out<% end %></li>
        <% else %>
        <li><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-log-in"></span> Sign in<% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <!-- <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p> -->
    </div>
    <div class="col-sm-8 text-left"> 
      <h2>Edit a contact</h2>
      <%= notice %>
      <%= alert %>
      <%= form_for @contact do |f| %>
      <span><%= f.label :name %></span><br>
      <span><%= f.text_field :name , placeholder: "Enter full name", class: 'input_span' %></span><br>
      <span><%= f.label :email %></span><br>
      <span><%= f.text_field :email , placeholder: "Enter email", class: 'input_span'%></span><br>
      <span><%= f.label :phone_number %></span><br>
      <span><%= f.text_field :phone_number , placeholder: "Enter phone numbers in , separated format", class: 'input_span'%></span><br>
      <span><%= f.label :address %></span><br>
      <span><%= f.text_field :address , placeholder: "Enter address", class: 'input_span'%></span><br>
      <span><%= f.submit "submit" %></span>
      <% end %>
    </div>
    <div class="col-sm-2 sidenav">
      <div class="well">
      	<%= link_to 'All Contect',contacts_path %>
        <!-- <p>ADS</p> -->
      </div>
      <div class="well">
        <!-- <p>ADS</p> -->
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer </p>
</footer>

</body>
</html>

app/views/contacts/failure.html.erb
<h2> Authentication has failed.</h2>

app/views/contacts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <!-- <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
  <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>                  
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%if current_user %>

        <li><%= link_to destroy_user_session_path , method: :delete do %><span class="glyphicon glyphicon-log-in"></span> Sign out<% end %></li>
        <% else %>
        <li><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-log-in"></span> Sign in<% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <!-- <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p> -->
    </div>
    <div class="col-sm-8 text-left"> 
      <%= form_tag contacts_path, method: :get do %>
  <div class="field">
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
  </div>
<% end %>
      <h2> All contacts</h2>
      <%= notice %>
      <%= alert %> 
      <strong><%= link_to "Download as CSV", contacts_path(:format => "csv")%></strong> 
      <strong><%= link_to "Import contact from gmail", "/contacts/gmail"%></strong>          
      <table class="table">
        

          <tr>
            <th class="col-md-2">Name</th>
            <th class="col-md-2">Email</th>            
            <th class="col-md-3">Phone Numbers</th>
            <th class="col-md-3">Address</th>
            <th class="col-md-2">Action</th>            
          </tr>
        <% @contacts.each do |c|%>

          <tr>
            <td class="col-md-2"><%=c.name%></td>
            <td class="col-md-2"><%=c.email%></td>
            <td class="col-md-3"><%=c.phone_number%></td>
            <td class="col-md-3"><%=c.address%></td>
            <td class="col-md-2">
              <%= link_to("Show", contact_path(c)) %>
              <%= link_to("Edit", edit_contact_path(c)) %>
              <%= link_to("Delet", contact_path(c), method: :delete)   %>
            </td>
          </tr> 
          <% end %>
      </table>
      <%= will_paginate @posts %>
    </div>
    <div class="col-sm-2 sidenav">
      <div class="well">
        <%= link_to 'New Contect',new_contact_path %>
        <!-- <p>ADS</p> -->
      </div>
      <div class="well">
        <!-- <p>ADS</p> -->
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer </p>
</footer>

</body>
</html>

app/views/contacts/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%if current_user %>

        <li><%= link_to destroy_user_session_path do %><span class="glyphicon glyphicon-log-in"></span> Sign out<% end %></li>
        <% else %>
        <li><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-log-in"></span> Sign in<% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <!-- <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p> -->
    </div>
    <div class="col-sm-8 text-left"> 
      <h2>Create a contact</h2>
      <%= notice %>
      <%= alert %>
      <%= form_for(:contact, :url => {:action => 'create'}) do |f| %>
      <span><%= f.label :name %></span><br>
      <span><%= f.text_field :name , placeholder: "Enter full name", class: 'input_span' %></span><br>
      <span><%= f.label :email %></span><br>
      <span><%= f.text_field :email , placeholder: "Enter email", class: 'input_span'%></span><br>
      <span><%= f.label :phone_number %></span><br>
      <span><%= f.text_field :phone_number , placeholder: "Enter phone numbers in , separated format", class: 'input_span'%></span><br>
      <span><%= f.label :address %></span><br>
      <span><%= f.text_field :address , placeholder: "Enter address", class: 'input_span'%></span><br>
      <span><%= f.submit "submit" %></span>
      <% end %>
    </div>
    <div class="col-sm-2 sidenav">
      <div class="well">
      	<%= link_to 'All Contect',contacts_path %>
        <!-- <p>ADS</p> -->
      </div>
      <div class="well">
        <!-- <p>ADS</p> -->
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer </p>
</footer>

</body>
</html>

app/views/contacts/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%if current_user %>

        <li><%= link_to destroy_user_session_path do %><span class="glyphicon glyphicon-log-in"></span> Sign out<% end %></li>
        <% else %>
        <li><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-log-in"></span> Sign in<% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <!-- <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p>
      <p><a href="#">Link</a></p> -->
    </div>
    <div class="col-sm-8 text-left"> 
      <h2>Contact Details</h2>
      <%= notice %>
      <%= alert %>
      <table>
          <tr>
            <th class="col-md-3">Name</th>
            <th class="col-md-3">Email</th>            
            <th class="col-md-3">Address</th>
            <th class="col-md-3">Phone Numbers</th>            
          </tr>
          <tr>
            <td class="col-md-3"><%=@contact.name%></td>
            <td class="col-md-3"><%=@contact.email%></td>
            <td class="col-md-3"><%=@contact.address%></td>
            <td class="col-md-3"><ol><% @phone_numbers.each do |p| %>
                                <li><%= p.number %> </li>  
                                <% end %></ol>
            </td>
          </tr>          
      </table>
    </div>
    <div class="col-sm-2 sidenav">
      <div class="well">
        <%= link_to 'All Contect',contacts_path %>
        <!-- <p>ADS</p> -->
      </div>
      <div class="well">
        <!-- <p>ADS</p> -->
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer </p>
</footer>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= render 'share/header' %>
<%= yield %>

</body>
  <%= javascript_include_tag 'creative' %>

</html>

app/views/layouts/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p> -->            
<%= yield %>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'share/header' %>
<%= yield %>

</body>
  <%= javascript_include_tag 'creative' %>

</html>